%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(my_chat_service_thrift).
-behaviour(thrift_service).


-include("my_chat_service_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% sendMessage(This, SenderId, RecieverId, Message)
function_info('sendMessage', params_type) ->
  {struct, [{1, i32},
          {2, i32},
          {3, string}]}
;
function_info('sendMessage', reply_type) ->
  {struct, []};
function_info('sendMessage', exceptions) ->
  {struct, []}
;
% recieveMessage(This, SenderId, RecieverId, Message)
function_info('recieveMessage', params_type) ->
  {struct, [{1, i32},
          {2, i32},
          {3, string}]}
;
function_info('recieveMessage', reply_type) ->
  {struct, []};
function_info('recieveMessage', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

